### ISSUE TITLE
Can't reliably create an X509 cert

### ISSUE THREAD

**Issue by mcepl** [mcepl/M2Crypto#2]
Originally https://github.com/M2Crypto/M2Crypto/issues/10 by @hufman:

I found some example code and made a simple helper function to easily generate certs. However, I found that it was randomly segfaults. I posted a test case on https://github.com/hufman/m2crypto_crash with a Travis build setup showing the crash.
Am I doing something wrong in my cert building?

From other tests I've done, it crashes at the signing step. I left out the log tracing from this example test, but they can easily be added back in.

**Comment by mcepl** [comment]
Filed as https://gitlab.com/m2crypto/m2crypto/issues/45

**Comment by hufman** [comment]
Thanks!

**Comment by mcepl** [comment]
Communication continues upstream.
