### ISSUE TITLE
Mass announcement

### ISSUE THREAD

**Issue by mcepl** [mcepl/M2Crypto#5]
@adrianmoisey @balajikumara @bbhoss @bsmartt13 @danmcd @destijl @dionyziz @dsoprea @edevil @floppym @gregwym @grrrrrrrrr @guilbep @HanSooloo @hcastilho @hufman @idgserpro @isokrates @JKDingwall @joejulian @kittozheng @kuba @martinpaljak @microcai @mitghi @mtrmac @NDavidBrown @neonknight @novocaine @pidydx @pyeekwr @RobertLarsen @rockymeza @ryanneufeld @simsong @skyronic @slamora @ThomasWaldmann @tingtingtwice @tricoder42 @ttanner @wenjianhn @xiahaihong @y2h4ck

If anybody is interested in the old M2Crypto code with just minimal maintenance (fixing bugs only), you can find it (with a list of known bugs) at https://gitlab.com/mcepl/m2crypto

This is **NOT** the official upstream repo for the PyPI package (which is https://github.com/martinpaljak/M2Crypto), just a basis for the maintenance in some Linux distros.

**Comment by dsoprea** [comment]
You're simply, official stating that yours is a legacy variation? For our references, at what point in its history was M2Crypto forked into the two separate ones?

**Comment by destijl** [comment]
I honestly have no idea what's happening with M2Crypto.  So you seem to have deleted (I get a 404) what I considered to be the official repo:
https://github.com/M2Crypto/M2Crypto/

and put a copy of it here (the gitlab version seems to have some later commits that this mcepl/M2Crypto repo does not):
https://gitlab.com/mcepl/m2crypto

and are now announcing this:
https://github.com/martinpaljak/M2Crypto

is the official repo, which is surprising since this:
https://github.com/martinpaljak/M2Crypto/blob/master/README.md

Says it will be moved to:
https://github.com/M2Crypto/M2Crypto/

???

If you wanted to move the code from martinpaljak/M2Crypto into M2Crypto/M2Crypto/ it seems like there are much better ways to do this using branches that don't require removing the whole repo. At least that way we could see what the changes to the current official code were and keep the history from the old repo.

Can you clear up what the plan is here?

**Comment by mcepl** [comment]
> I honestly have no idea what's happening with M2Crypto. So you seem to have deleted (I get a 404) what I considered to be the official repo:
> https://github.com/M2Crypto/M2Crypto/

That’s the problem. Despite what some sources on the Internet said (and sometime even what they are saying right now) it has never been the official repo. PyPI package (since it moved from http://chandlerproject.org/Projects/MeTooCrypto) has been always maintained on https://github.com/martinpaljak/M2Crypto

There were plans to make M2Crypto/M2Crypto to be the official repo, but they have never materialized.

> is the official repo, which is surprising since this:
> https://github.com/martinpaljak/M2Crypto/blob/master/README.md
> 
> Says it will be moved to:
> https://github.com/M2Crypto/M2Crypto/

Yes, see https://github.com/martinpaljak/M2Crypto/pull/73

> If you wanted to move the code from martinpaljak/M2Crypto into M2Crypto/M2Crypto/

No, that was not my intention.

BTW, the last shared commit was tag https://github.com/martinpaljak/M2Crypto/commit/507e22b4320a15f3c6cf66ac0d4fa1d87e4db3fb

**Comment by ruskotron** [comment]
So in a nutshell, the new official repo is https://github.com/martinpaljak/M2Crypto

FYI at this stage two items in this migration seem to be outstanding:
 * [Pull request](https://github.com/martinpaljak/M2Crypto/pull/73) updating the README hasn't been accepted
 * [pypi index](https://pypi.python.org/pypi/M2Crypto/) still points at the obsolete repo.

I hope this comment helps people who are as confused as I have been just now!

**Comment by joejulian** [comment]
Lat commit was May 6, 2014. I think that's dead too.

**Comment by mcepl** [comment]
It certainly is dead. I have a message from @martinpaljak giving up on M2Crypto maintenance. I will restore back M2Crypto/M2Crypto repository, but currently I am snowed in the work. Give me a moment, please!

**Comment by idgserpro** [comment]
@mcepl Do you have pypi permission as well?

**Comment by joejulian** [comment]
Thank you mcepl! :+1:

**Comment by ruskotron** [comment]
Thank you! :)

**Comment by Kendos-Kenlen** [comment]
If someone restart to work on M2Crypto, could he fix this issue ? https://github.com/martinpaljak/M2Crypto/issues/60

The issue is still present (as I said in my comment), some work have been done but I don't know if it correct the problem or not (at least, the 0.22.3 version doesn't correct it).

**Comment by mtrmac** [comment]
See PR martinpaljak/M2Crypto#75, perhaps as well as the full set of patches in Fedora packages based on 0.22.1. I am not, at least in the short term, likely to update to 0.22.3 and provide a fully rebased set of patches.

**Comment by mcepl** [comment]
OK, so here is the deal:

Next completely official only master repo will be https://gitlab.com/m2crypto/m2crypto/ (yes, I would prefer to move to GitLab). Currently, its master branch is reset to 0.21.1 tag with some hopefully not very controversial fixes.

All Fedora/RHEL patches are in https://gitlab.com/m2crypto/m2crypto/merge_requests/1 **PLEASE** review this merge request, comment on it (especially, @mtrmac , there are some commits labelled FIXME, where I am really not sure about the metadata, or whether the commit should be included at all).

Please, test this on other platforms (especially Mac/Windows, I don't have the machine), and file issues in https://gitlab.com/m2crypto/m2crypto/issues

When the `fedora` branch (and some possibly horrible issues which will turn up) is merged, I will mark it as `0.22.4` and push to PyPI. Then we can start to deal with any new issues etc.

The general plan for M2Crypto is that from now on, the maintenance should be very conservative, just fixing bugs and adding only such additional features as they will turn to be necessary for further use. No new features or large changes are expected.

**Comment by simsong** [comment]
By conservative, do you mean that it will never support Python 3?

**Comment by mcepl** [comment]
> By conservative, do you mean that it will never support Python 3?

Good question. There is [the branch `python3`](https://gitlab.com/m2crypto/m2crypto/tree/python3) in the upstream repository. It kind of works, but it needs rebase, finishing testsuite, and then the whole thing should be somehow merged into the main tree. I welcome all merge requests leading towards doing this work, but I don’t expect much work done by myself.

So, I am not against it, but the main purpose of this project is now to keep the code alive for those who still use it. However, when you are doing port of your program to python3, it should be worthy of either using the native SSL parts (mind you, m2crypto probably conflicts with the native SSL facilities in all versions of python; certainly combination of the two is unsupported now) or for example porting to [`python-cryptography`](https://github.com/pyca/cryptography) which is actively developed for both python2 and python3.

**Comment by simsong** [comment]
Okay. I'm currently using M2Crypto for certificate decoding. I need to see
if the Python native SSL facilities provide support for reading parts of
the certificate and decoding them.

**Comment by novocaine** [comment]
They don't.

For python 3, we have switched to python-cryptography, which is in a much
better state anyway (on mcepl's suggestion a few months back). It seems to
cover everything we used M2Crypto for.

**Comment by mcepl** [comment]
OK, what will happen to be the next upstream `master` is now https://gitlab.com/m2crypto/m2crypto/merge_requests/1 (the history is now so messy, that it is better to look at 
https://gitlab.com/m2crypto/m2crypto/merge_requests/1/commits which is current). It is now on the top of the release `0.21.1`.

**PLEASE**, all of you interested in M2Crypto. Take a look at it and comment on it, because this is our future. Please.

**Comment by simsong** [comment]
Thanks for your contributions. It looks clean, but as you said, there is no Python 3.0 future here.

**Comment by mcepl** [comment]
> there is no Python 3.0 future here.

well, perhaps ... https://github.com/davidhalter/jedi/issues/630 ... I won't do it myself, but if anybody want to participate in the effort I am all ears.

**Comment by mcepl** [comment]
OK, that pull request should now satisfy all tests ... could somebody not on Fedora/RHEL/CentOS (where the situation is a bit different) run `python setup.py test`?

Thank you

**Comment by Kendos-Kenlen** [comment]
HI,

I built it on archlinux (with python 2.7 + swig 3.0.7) and it crashed. This is the logs: https://gist.github.com/Kendos-Kenlen/9622b43cfa16ed572768

I'm sorry if I missed something, I'm not familiar nor with Python, nor with M2Crypto.

**Comment by mcepl** [comment]
@Kendos-Kenlen Please, file a ticket at https://gitlab.com/m2crypto/m2crypto/issues with this log attached (you can just drag&drop a text file to the comment box) and versions of gcc, python, and openssl. Thank you.

**Comment by idgserpro** [comment]
@mcepl @martinpaljak  I think after notifying all issues and pull request from the repository https://github.com/martinpaljak/M2Crypto, it should be detected.

**Comment by tomato42** [comment]
@mcepl I don't know about gitlab, but for github, there's AppVeyor for CI on windows

**Comment by mcepl** [comment]
> I think after notifying all issues and pull requests from the repository https://github.com/martinpaljak/M2Crypto, it should be deleted.

It is not mine repo, so I cannot do anything about. But yes, of course, I would welcome, if at least martin's repo was fork of mine (which will be always a mirror of the main gitlab's one).

**Comment by mcepl** [comment]
So, this is the last call. Thank you very much for all comments (and issues you found), but unless something serious happens, I will merge the request on Monday morning (CEST). So, if you want to have something not be in the first release, let me know.

**Comment by cdeccio** [comment]
@mcepl by "first release" do you mean that you plan to bump the version and tag a release after merging all the pull requests that currently exist?  I have patches from which I am building pull requests, but it would be nice to do it from the new upstream and that the tag/release might consider these new requests.

**Comment by mcepl** [comment]
@cdeccio no, by the new release I mean, that for now I am going to:

1. make the merge of the https://gitlab.com/m2crypto/m2crypto/merge_requests/1 as it is now and call it ``master``, then I will release it as ``0.22.4`` (yes, it is more or less regression against the current 0.22.3)
2. Remove issue tracker from this repo, so all discussion should move to GitLab.
3. work on two really ugly bugs which still remain https://gitlab.com/m2crypto/m2crypto/issues/51 and https://gitlab.com/m2crypto/m2crypto/issues/57 (yes, testsuite fails on ArchLinux and Windows and I know about it) and collecting any new angry responses about breakage.
4. hopefully soon resolve all https://gitlab.com/m2crypto/m2crypto/milestones/2 and release the result as ``0.22.5``
5. Go on from there.

Concerning your patches, I probably won't accept anything for ``0.22.4``, but otherwise all issues, patches, merge requests are more than welcome on https://gitlab.com/m2crypto/m2crypto/issues

**Comment by cdeccio** [comment]
@mcepl thanks for the clarification.  I'll get my changes ready (just working on unit tests), so they can be pulled in whenever it makes sense.

Thanks for taking the lead on this!

**Comment by mcepl** [comment]
So, OK, the first step from https://github.com/mcepl/M2Crypto/issues/5#issuecomment-147423376 is done, now the second step. Which means removing issue tracker here, so closing this issue.

Thank you for all comments on the upstream merge request. Thank you!

Please, continue the discussion on https://gitlab.com/m2crypto/m2crypto/issues
